name: Push component to ESP-Registry
on:
  push:
    tags:
      - v*
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "tetris"
          version: ${{ github.ref_name }}
          namespace: "0xjmux"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}